spring:
  application:
    name: user-service
  datasource:
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/user_service"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8083